const MSWebSimulator = {
  Requests: true,
  BytesReceived: true,
  BytesSent: true,
  Http101: false,
  Http2xx: false,
  Http3xx: false,
  Http401: false,
  Http403: false,
  Http404: true,
  Http406: false,
  Http4xx: false,
  Http5xx: false,
  MemoryWorkingSet: false,
  AverageMemoryWorkingSet: true,
  AverageResponseTime: false,
  HttpResponseTime: true,
  FunctionExecutionUnits: false,
  FunctionExecutionCount: true,
  AppConnections: false,
  Handles: false,
  Threads: true,
  PrivateBytes: false,
  IoReadBytesPerSecond: false,
  IoWriteBytesPerSecond: false,
  IoOtherBytesPerSecond: false,
  RequestsInApplicationQueue: false,
  CurrentAssemblies: false,
  TotalAppDomains: false,
  TotalAppDomainsUnloaded: false,
  Gen0Collections: false,
  Gen1Collections: false,
  Gen2Collections: false,
  HealthCheckStatus: false,
  FileSystemUsage: true,
};

const MSStorageSimulator = {
  UsedCapacity: false,
  Transactions: false,
  Ingress: false,
  Egress: false,
  SuccessServerLatency: false,
  SuccessE2ELatency: false,
  Availability: true,
};

const MSInsightsSimulator = {
  availabilityResults: {
    count: false,
    duration: false,
  },
  browserTimings: {
    networkDuration: false,
    processingDuration: false,
    receiveDuration: false,
    sendDuration: false,
    totalDuration: false,
  },
  dependencies: {
    count: false,
    duration: false,
    failed: false,
  },
  pageViews: {
    count: false,
    duration: false,
  },
  performanceCounters: {
    requestExecutionTime: false,
    requestsInQueue: false,
    requestsPerSecond: false,
    exceptionsPerSecond: false,
    processIOBytesPerSecond: false,
    processCpuPercentage: false,
    processorCpuPercentage: false,
    memoryAvailableBytes: false,
    processPrivateBytes: false,
  },
  requests: {
    duration: true,
    count: true,
    failed: false,
    rate: false,
  },
  exceptions: {
    count: false,
    browser: false,
    server: false,
  },
  traces: {
    count: false,
  },
};

export { MSWebSimulator, MSStorageSimulator, MSInsightsSimulator };
